services:
  komodo:
    image: ghcr.io/moghtech/komodo:latest
    labels:
      komodo.skip: # Prevent Komodo from stopping itself with StopAllContainers
    restart: unless-stopped
    logging:
      driver: local
    networks:
      - default
    ports:
      - 9120:9120
    env_file: ./komodo.env
    environment:
      KOMODO_DATABASE_ADDRESS: 172.17.0.1:27017
    volumes:
      ## Core cache for repos for latest commit hash / contents
      - repo-cache:/repo-cache

  periphery:
    image: ghcr.io/moghtech/periphery:latest
    labels:
      komodo.skip: # Prevent Komodo from stopping itself with StopAllContainers
    restart: unless-stopped
    logging:
      driver: local
    networks:
      - default
    env_file: ./komodo.env
    environment:
      PERIPHERY_REPO_DIR: /etc/komodo/repos
      PERIPHERY_STACK_DIR: /etc/komodo/stacks
      PERIPHERY_SSL_ENABLED: false
      PERIPHERY_SSL_KEY_FILE: /etc/komodo/ssl/key.pem
      PERIPHERY_SSL_CERT_FILE: /etc/komodo/ssl/cert.pem
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home:/host/home/
      - /etc/komodo:/etc/komodo
      - /proc:/proc

volumes:
  repo-cache:

