services:
  portainer:
    #image: portainer/portainer-ce:latest
    image: ngxson/portainer-ce-without-annoying:latest
    hostname: portainer
    restart: always
    ports:
      - 8001:9000
    volumes:
      - ./data:/data
      - /var/run/docker.sock:/var/run/docker.sock
