services:
  npm:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    network_mode: host
    #ports:
    #  - '80:80'
    #  - '81:81'
    #  - '443:443'
    expose:
      - '80'
      - '81'
      - '443'
    volumes:
      - ./data:/data
      - ./data/letsencrypt:/etc/letsencrypt
