receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4310
      http:
        endpoint: 0.0.0.0:4311


processors:
  batch:
    timeout: 10s
  resourcedetection/docker:
    detectors: [env, docker]
    timeout: 2s
    override: false

exporters:
  debug:
    verbosity: detailed

  otlphttp:
    endpoint: http://tempo:4318

  prometheus:
    endpoint: 0.0.0.0:8889


service:
  telemetry:
    logs:
      level: "info"
    metrics:
      address: ":8888"
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [otlphttp]
    metrics:
      receivers: [otlp]
      processors: [batch, resourcedetection/docker]
      exporters: [prometheus]
