receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4310

processors:
  batch:
    timeout: 10s
  resourcedetection/docker:
    detectors: [env, docker]
    timeout: 2s
    override: false

exporters:
  debug:
    verbosity: detailed

  prometheus:
    endpoint: 0.0.0.0:8889

  otlphttp/tempo:
    endpoint: http://tempo:4318

  otlphttp/loki:
    endpoint: http://loki:3100/otlp

service:
  telemetry:
    logs:
      level: "info"
    metrics:
      address: ":8888"
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [otlphttp/tempo]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlphttp/loki]
    metrics:
      receivers: [otlp]
      processors: [batch, resourcedetection/docker]
      exporters: [prometheus]
