global:
  scrape_interval: 10s

scrape_configs:
  - job_name: meta-otel-collector
    static_configs:
      - targets: ['172.17.0.1:8888']
  - job_name: otel-collector
    static_configs:
      - targets: ['172.17.0.1:8889']
