global:
  scrape_interval: 10s

scrape_configs:
  - job_name: meta-otel-collector
    static_configs:
      - targets: ['172.17.0.1:8888']
  - job_name: otel-collector
    static_configs:
      - targets: ['172.17.0.1:8889']
  - job_name: pushgateway
    honor_labels: true
    static_configs:
      - targets: ['172.17.0.1:9091']
  - job_name: upitmekuma
    static_configs:
      - targets: ['oracle:3001']
