services:
  caddy:
    build: .
    image: kratos-caddy:local
    restart: unless-stopped
    network_mode: host
    command: ["caddy"]
    env_file:
      - ./caddy.env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ../../.data/caddy/data:/data
      - ../../.data/caddy/config:/etc/caddy
