services:
  pushgateway:
    image: prom/pushgateway
    ports:
      - 127.0.0.1:9091:9091
    depends_on:
      - prometheus

  node_exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: node_exporter
    command:
      - --path.rootfs=/host
    network_mode: host
    pid: host
    restart: unless-stopped
    volumes:
      - '/:/host:ro,rslave'
    depends_on:
      - prometheus

  prometheus:
    image: prom/prometheus:latest
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --web.enable-remote-write-receiver
    user: "10001:10001"
    ports:
      - 127.0.0.1:9090:9090
    volumes:
      - ../configs/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ../.data/prometheus:/prometheus

  loki:
    image: grafana/loki:latest
    command: [ "-config.file=/etc/loki/local-config.yaml" ]
    user: "10001:10001"
    ports:
      - 127.0.0.1:3100:3100
    restart: unless-stopped
    volumes:
      - ../configs/loki.yml:/etc/loki/local-config.yaml
      - ../.data/loki:/var/loki
    depends_on:
      - grafana

  tempo:
    image: grafana/tempo:latest
    command: [ "-config.file=/etc/tempo.yml" ]
    user: "10001:10001"
    volumes:
      - ../configs/tempo.yml:/etc/tempo.yml
      - ../.data/tempo:/var/tempo
    ports:
      - 127.0.0.1:3200:3200 # tempo
      - 127.0.0.1:4318:4318 # otlp grpc

  grafana:
    image: grafana/grafana-oss:latest
    restart: unless-stopped
    env_file: ./grafana.env
    user: "10001:10001"
    ports:
      - 127.0.0.1:3001:3000
    volumes:
      - ../.data/grafana:/var/lib/grafana
    depends_on:
      - tempo
      - prometheus

  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    command:
      - --config=/etc/otel-collector.yml
    ports:
      - 127.0.0.1:4310:4310 # Incoming OTel gRPC 
      - 127.0.0.1:4311:4311 # Incoming OTel HTTP (Proto/JSON)
      - 127.0.0.1:8888:8888 # Outgoing metrics about the Collector (Diagnostic)
      - 127.0.0.1:8889:8889 # Outgoing metrics from the Collector 
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ../configs/otel-collector.yml:/etc/otel-collector.yml
    depends_on:
      - grafana
