volumes:
  grafana-storage: {}

services:
  init:
    image: &tempoImage grafana/tempo:latest
    user: root
    entrypoint:
      - "chown"
      - "10001:10001"
      - "/var/tempo"
    volumes:
      - ./data:/var/tempo

  tempo:
    image: *tempoImage
    command: [ "-config.file=/etc/tempo.yml" ]
    volumes:
      - ../configs/tempo.yml:/etc/tempo.yml
      - ./data:/var/tempo
    ports:
      - 3200:3200 # tempo
      - 4318:4318 # otlp grpc
    depends_on:
      - init

  otel-collector:
    image: otel/opentelemetry-collector:latest
    command: [ "--config=/etc/otel-collector.yml" ]
    env_file: ./collector.env
    ports:
      - 4310:4310 # Incoming OTel gRPC 
      - 4311:4311 # Incoming OTel HTTP (Proto/JSON)
      - 8888:8888 # Outgoing metrics about the Collector (Diagnostic)
      - 8889:8889 # Outgoing metrics from the Collector 
    volumes:
      - ../configs/otel-collector.yml:/etc/otel-collector.yml
    depends_on:
      - grafana

  prometheus:
    image: prom/prometheus:latest
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --web.enable-remote-write-receiver
      #- --enable-feature=otlp-write-receiver
    volumes:
      - ../configs/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana-oss
    restart: unless-stopped
    env_file: ./grafana.env
    ports:
      - '3001:3000'
    volumes:
      - grafana-storage:/var/lib/grafana
    depends_on:
      - tempo
      - prometheus
